spring:
  config:
    import:
      - logging.yml
      - application-db.yml

  profiles:
    active:
      - dev
    group:
      dev: "db-dev"
      prod: "db-prod"
      test: "db-test"
    include:
      - db
