spring:
  config:
    activate:
      on-profile: "cors-dev"

client:
  origin: localhost:8080

---
spring:
  config:
    activate:
      on-profile: "cors-prod"

client:
  origin: ${CLIENT_ORIGIN}


