spring:
  profiles:
    active:
      - dev
    group:
      dev: "db-dev, security-dev"
      prod: "db-prod, security-prod"
      test: "db-test, security-test"
    include:
      - db
      - security
