name: BE - CD

on:
  push:
    branches: [main]
    paths:
      [
        "src/**",
        "build.gradle",
      ]

permissions:
  contents: read

jobs:
  be-test:
    name: test spring boot
    runs-on: ubuntu-20.04

    steps:
      - name: setup repo
        uses: actions/checkout@v3

      - name: setup java 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: use gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: grant execute permission for gradlew
        run: chmod +x gradlew

      - name: build with gradle
        run: ./gradlew build

      - name: docker build & push
        run: |
          docker login -u "${{ secrets.DOCKER_ID }}" -p "${{ secrets.DOCKER_PASSWORD }}"
          docker build -f Dockerfile -t "${{ secrets.DOCKER_REPO }}"/kkeuroolryo .
          docker push "${{ secrets.DOCKER_REPO }}"/kkeuroolryo
